server:
  port: 8090

spring:
  rabbitmq:
    host: localhost
    username: admin
    password: admin
    port: 5672

chat:
  teams:
    webhook:
      url: "https://reedelsevier.webhook.office.com/webhookb2/e7e0cced-9e66-438b-b1b8-584f5177c86b@9274ee3f-9425-4109-a27f-9fb15c10675d/IncomingWebhook/86affec51e9643b1a629ac74fdf7bdb3/9f1fdd57-0e14-418f-af9b-6c3a55f3d400"